# This file is used as the [matrix](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)
# key in the test job defined in `.github/workflows/ci.yml`
# after being processed with `.github/bin/build-matrix-from-impacted.py`
# to exclude modules without any changes.
include:
  - modules:
    - core/trino-main
    - modules:
      - testing/trino-tests
    - modules:
      - plugin/trino-raptor-legacy
    - modules:
      - plugin/trino-accumulo
    - modules:
      - plugin/trino-cassandra
    - modules:
      - plugin/trino-clickhouse
    - modules:
      - plugin/trino-hive
      - lib/trino-orc
    - modules:
      - plugin/trino-hive
      - lib/trino-parquet
      options: "-P test-parquet"
    - modules:
      - plugin/trino-hive
      options: "-P test-failure-recovery"
    - modules:
      - plugin/trino-mongodb
      - plugin/trino-kafka
      - plugin/trino-elasticsearch
    - modules:
      - plugin/trino-elasticsearch
      options: "-P test-stats"
    - modules:
      - plugin/trino-redis
    - modules:
      - plugin/trino-sqlserver
      - plugin/trino-postgresql
      - plugin/trino-mysql
    - modules:
      - plugin/trino-memsql
    - modules:
      - plugin/trino-oracle
    - modules:
      - plugin/trino-kudu
    - modules:
      - plugin/trino-iceberg
      - plugin/trino-druid
    - modules:
      - plugin/trino-phoenix
      - plugin/trino-phoenix5
    - modules:
      - plugin/trino-bigquery
